# Generated by Django 3.0.3 on 2020-03-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultanalysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
