# Generated by Django 3.0.3 on 2020-03-19 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resultanalysis', '0002_batches_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='batches',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
