# Generated by Django 3.0.3 on 2020-03-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultanalysis', '0004_auto_20200320_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='thumb',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
