# Generated by Django 3.0.3 on 2020-03-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultanalysis', '0005_auto_20200320_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batches',
            name='thumb',
            field=models.ImageField(blank=True, default='assets/default.jpg', upload_to=''),
        ),
    ]
