# Generated by Django 3.0.3 on 2020-03-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultanalysis', '0008_auto_20200320_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='excel_raw_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=30)),
                ('batch_id', models.IntegerField()),
                ('sem_id', models.IntegerField()),
                ('excel_data', models.FileField(upload_to='')),
            ],
        ),
    ]
