# Generated by Django 3.0.3 on 2020-03-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultanalysis', '0009_excel_raw_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel_raw_data',
            name='batch_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='excel_raw_data',
            name='batch_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='excel_raw_data',
            name='sem_id',
            field=models.IntegerField(blank=True),
        ),
    ]
