# Generated by Django 3.0.3 on 2020-03-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultanalysis', '0010_auto_20200321_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excel_raw_data',
            name='batch_id',
        ),
        migrations.RemoveField(
            model_name='excel_raw_data',
            name='batch_name',
        ),
        migrations.RemoveField(
            model_name='excel_raw_data',
            name='sem_id',
        ),
    ]
