# Generated by Django 3.0.3 on 2020-03-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultanalysis', '0021_auto_20200327_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='arrears_count_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(blank=True, max_length=30)),
                ('batch_id', models.IntegerField(default=1)),
                ('excel_data', models.FileField(upload_to='')),
            ],
        ),
    ]
